### ISSUE TITLE
KeyError: 'code' when trying to send a search query

### ISSUE THREAD

**Issue by kosc** [fluquid/yandex-search#1]
Hello! I'm trying to use this module installed from pip in Gentoo (Gentoo Base System release 2.3) under IPython 5.3.0 with Python 3.5.3 and getting the following error:

`In [10]: yandex.search('"Interactive Saudi"')
    ...: 
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-10-4745561838dc> in <module>()
----> 1 yandex.search('"Interactive Saudi"')

/home/kosc/.local/lib64/python3.5/site-packages/yandex_search/__init__.py in search(self, query, page, group_by_domain)
    166                               page=page,
    167                               group_by_domain=group_by_domain)
--> 168         return self._parse_xml(xml)

/home/kosc/.local/lib64/python3.5/site-packages/yandex_search/__init__.py in _parse_xml(self, xml)
    140         """ parse information from xml into YandexResult object """
    141         root = etree.XML(xml)
--> 142         self._raise_on_error(root)
    143 
    144         # request = root.xpath('./request')

/home/kosc/.local/lib64/python3.5/site-packages/yandex_search/__init__.py in _raise_on_error(self, tree)
    102         if errors:
    103             error = errors[0]
--> 104             code = int(error.attrib['code'])
    105             message = ' '.join(error.xpath('.//text()'))
    106 

src/lxml/lxml.etree.pyx in lxml.etree._Attrib.__getitem__ (src/lxml/lxml.etree.c:68664)()

KeyError: 'code'
`

**Comment by codinguncut** [comment]
Hi, I will look into it, looks like bad parsing of error message.
did you sign ip with yndex as per readme?
Johannes

**Comment by codinguncut** [comment]
Hi kosc,

I have just released a new version that will give better log messages.
It appears that the result you get back from yandex contains an `<error>` tag but no `<error code="NN">` code attribute.
Could you please install the latest version `pip install --upgrade yandex-search` and tell me the new log output?

**Comment by kosc** [comment]
Thanks you! After upgrade I've got following traceback:

`ERROR:root:'code'
Traceback (most recent call last):
  File "/home/kosc/.local/lib64/python3.5/site-packages/yandex_search/__init__.py", line 107, in _raise_on_error
    code = int(error.attrib['code'])
  File "src/lxml/lxml.etree.pyx", line 2467, in lxml.etree._Attrib.__getitem__ (src/lxml/lxml.etree.c:70679)
KeyError: 'code'
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/home/kosc/.local/lib64/python3.5/site-packages/yandex_search/__init__.py in _raise_on_error(self, tree, xml)
    106             try:
--> 107                 code = int(error.attrib['code'])
    108             except (KeyError, ValueError) as e:

src/lxml/lxml.etree.pyx in lxml.etree._Attrib.__getitem__ (src/lxml/lxml.etree.c:70679)()

KeyError: 'code'

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
<ipython-input-3-6916afbba8e1> in <module>()
----> 1 yandex.search("купить камеру")

/home/kosc/.local/lib64/python3.5/site-packages/yandex_search/__init__.py in search(self, query, page, group_by_domain)
    174                               page=page,
    175                               group_by_domain=group_by_domain)
--> 176         return self._parse_xml(xml)

/home/kosc/.local/lib64/python3.5/site-packages/yandex_search/__init__.py in _parse_xml(self, xml)
    148         """ parse information from xml into YandexResult object """
    149         root = etree.XML(xml)
--> 150         self._raise_on_error(root, xml)
    151 
    152         # request = root.xpath('./request')

/home/kosc/.local/lib64/python3.5/site-packages/yandex_search/__init__.py in _raise_on_error(self, tree, xml)
    109                 logging.exception(e)
    110                 raise Exception('unable to parse error code: ' +
--> 111                                 (xml if six.PY2 else xml.decode('utf-8')))
    112 
    113             message = ' '.join(error.xpath('.//text()'))

Exception: unable to parse error code: <?xml version="1.0" encoding="utf-8"?>
<yandexsearch version="1.0"><response date="20170612T134001"><error>You must accept the terms of the License Agreement to use this service</error></response></yandexsearch>

In [4]: yandex.search('"Interactive Saudi"')
ERROR:root:'code'
Traceback (most recent call last):
  File "/home/kosc/.local/lib64/python3.5/site-packages/yandex_search/__init__.py", line 107, in _raise_on_error
    code = int(error.attrib['code'])
  File "src/lxml/lxml.etree.pyx", line 2467, in lxml.etree._Attrib.__getitem__ (src/lxml/lxml.etree.c:70679)
KeyError: 'code'
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/home/kosc/.local/lib64/python3.5/site-packages/yandex_search/__init__.py in _raise_on_error(self, tree, xml)
    106             try:
--> 107                 code = int(error.attrib['code'])
    108             except (KeyError, ValueError) as e:

src/lxml/lxml.etree.pyx in lxml.etree._Attrib.__getitem__ (src/lxml/lxml.etree.c:70679)()

KeyError: 'code'

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
<ipython-input-4-4745561838dc> in <module>()
----> 1 yandex.search('"Interactive Saudi"')

/home/kosc/.local/lib64/python3.5/site-packages/yandex_search/__init__.py in search(self, query, page, group_by_domain)
    174                               page=page,
    175                               group_by_domain=group_by_domain)
--> 176         return self._parse_xml(xml)

/home/kosc/.local/lib64/python3.5/site-packages/yandex_search/__init__.py in _parse_xml(self, xml)
    148         """ parse information from xml into YandexResult object """
    149         root = etree.XML(xml)
--> 150         self._raise_on_error(root, xml)
    151 
    152         # request = root.xpath('./request')

/home/kosc/.local/lib64/python3.5/site-packages/yandex_search/__init__.py in _raise_on_error(self, tree, xml)
    109                 logging.exception(e)
    110                 raise Exception('unable to parse error code: ' +
--> 111                                 (xml if six.PY2 else xml.decode('utf-8')))
    112 
    113             message = ' '.join(error.xpath('.//text()'))

Exception: unable to parse error code: <?xml version="1.0" encoding="utf-8"?>
<yandexsearch version="1.0"><response date="20170612T134040"><error>You must accept the terms of the License Agreement to use this service</error></response></yandexsearch>
`

**Comment by codinguncut** [comment]
Hi kosc,

can you please go to https://xml.yandex.ru/settings/ and accept the "License Agreement" and `Save`.
I have updated the Readme to also reflect this better.

![2017-06-12 14_57_39-yandex xml](https://user-images.githubusercontent.com/2112583/27037371-abdbf0fc-4f7f-11e7-8193-48da4ff36501.png)

**Comment by kosc** [comment]
Ok, thank you, it works for me now.
